server:
  port: 9005
  servlet:
    context-path: /

spring:
  application:
    name: serverless-platform-selector-api
  
  datasource:
    url: jdbc:postgresql://localhost:5432/serverless_platform_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

# Application specific properties
app:
  encryption:
    secret-key: 12345678901234567890123456789012

# Logging configuration
logging:
  level:
    com.serverless.platformselector: INFO
    org.springframework.: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

#spring boot actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

  tracing:
    enabled: true
    sampling:
      probability: 1.0